sudo: required
services:
  - docker 

before_install:
  - docker build -t tantho/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tantho/react-test npm test

after_success:
  - docker build -t tranantho/multi-client ./client
  - docker build -t tranantho/multi-nginx ./nginx
  - docker build -t tranantho/multi-server ./server
  - docker build -t tranantho/multi-worker ./worker
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push these bad boys to docker hub
  - docker push tranantho/multi-client
  - docker push tranantho/multi-nginx
  - docker push tranantho/multi-server
  - docker push tranantho/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-701819526383
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY